### ISSUE TITLE
this 的觀念有誤

### ISSUE THREAD

**Issue by DerekHung** [104corp/f2e-technote#3]
this 在function 的時候取決於他是怎麼被『呼叫執行』的

例如：一般function
```javascript

var a = function() { console.log(this)}
a();

// window
```

這邊你可以把他想成 window.a()  因此是由window來呼叫a 這個function
這時候this 就會指向window

```javascript
var b = { a:function(){ console.log(this) }}
b.a();

// b:{ a.....}

```
其實對照上面就很清楚了，這時候就變成b 在執行這個function 因此很自然的this 就指到了b

而constructor (new) 為何不一樣？因為constructor 他會自己先產生一個空物件，然後讓這個空物件去執行他的constructor函式，做完constructor function 之後再賦值給宣告，如下

```javascript
var a = function(){ console.log(this)}
var con = new a();
==> {}.a()
==> con = {} // constructor temp object

// con: {}
```

**Comment by dazedbear** [comment]
this的部份做了較大範圍的更新，若有錯誤煩請再通知我做修正，感謝~

* [又愛又恨的this](https://github.com/104corp/f2e-technote/blob/master/Training/%E5%B0%8F%E9%AE%AE%E8%82%8917b/3-Function.md#又愛又恨的this)

**Comment by DerekHung** [comment]
看內容不太確定有沒有真的了解
下面有一個我之前自己練習弄的考題
可以試著做看看！

https://gist.github.com/DerekHung/f9c23e5b05989ca0b67fe839edd19921
