### ISSUE TITLE
CSS 練習

### ISSUE THREAD

**Issue by DerekHung** [104corp/f2e-technote#7]
17b

**Comment by TroyCode** [comment]
[](https://codepen.io/troywu/pen/GvYLYa)

**Comment by TacoUltoud** [comment]
https://codepen.io/ultoud/pen/rzqgOd

**Comment by polydragoncez** [comment]
https://jsfiddle.net/pxcwra8a/

**Comment by suy1000000** [comment]
https://codepen.io/suy1000000/pen/vJVMEj

**Comment by dtfcyhd80** [comment]
https://codepen.io/anon/pen/GvYegm

**Comment by chunghongke** [comment]
https://codepen.io/anon/pen/VzEOeO

**Comment by yochen1325117** [comment]
https://jsfiddle.net/ps09jhdw/

**Comment by PeterCHEN-JIANRONG** [comment]
https://codepen.io/JIAN-RONG/pen/rzqgwr
